#!/usr/bin/env python3
"""Regenerate cad/triskele_pattern.scad from Insert-air-tribe.stl.

    python3 trace_triskele.py            # rebuild the pattern file
    python3 trace_triskele.py --check    # verify only, write nothing

Run from coasters/. Needs OpenSCAD on PATH and Pillow. Output is
deterministic: rebuilding reproduces the pattern file, and therefore
coaster_triskele.stl, byte for byte.

Modelled on trace_tree_of_life.py, which is the worked example for
utilities/pattern_trace.py. Two differences from that script, both in the
trace recipe and both worth reading before copying this one:

  * THE PLATE LIES IN A DIFFERENT PLANE. Insert-tree.stl is a plate in XZ
    (thickness along Y); this one is a plate in YZ (thickness along X). The
    tree's `rotate([90,0,0])` is therefore wrong here, and so is the
    `mirror()` that compensated for it. See TRACE_SCAD below.

  * NOTHING IS FILTERED OUT BUT THE PLATE'S OWN BORDER. The tree's chain
    ring had to be discarded and redrawn because it was unprintable; this
    source measures healthy everywhere (spec section 3), so the whole design
    is kept -- centre spiral, three arms, 56 dots and four outer arcs.

The two verification steps in the middle are not ceremony. Every coaster in
this repo has had one of them come out wrong:

  * SENSE -- are the traced loops the artwork, or the hole around it? Here
    they are the artwork's cut strokes (this source, like Insert-tree.stl,
    is a plate with the design cut clean through), so callers SUBTRACT.
  * ORIENTATION -- a triskele is chiral, so a mirrored trace would reverse
    the direction the spirals turn. No derived number would say so.
"""
import os
import subprocess
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "utilities"))

from mesh_orient import load_oriented, plate_axis                  # noqa: E402
from pattern_trace import (emit_scad, nested, orientation_iou,     # noqa: E402
                           sense_of, trace_dxf)
from dxf_trace import polygon_area                                 # noqa: E402
from stl_io import load_stl                                        # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "Insert-air-tribe.stl")
OUT = os.path.join(HERE, "cad", "triskele_pattern.scad")
DXF = os.path.join(HERE, "cad", ".triskele_trace.dxf")      # intermediate

# The design's own outer radius (the outer edge of the four broken-ring
# arcs). This is the scale reference the coaster uses to land the pattern at
# r = 43, which puts the arcs' outer edge exactly on the rim's inner edge.
NATIVE_MAX_R = 47.1910
TARGET_R = 43.0
SCALE = TARGET_R / NATIVE_MAX_R

# Everything in the design sits inside r = 47.20; the only other component
# in the trace is the plate's own square border at r = 75.80. The gap is
# enormous, so this threshold is not a judgement call.
DESIGN_MAX_R = 50.0

# The reference face for both checks. The plate's two faces are the same
# design to IoU 0.997 (it is a straight through-cut, not an engraving), but
# the -58.0 face also carries four blind corner pockets that do not exist in
# a projection() shadow, and -60.5 is clean.
FACE_Z = -60.5

TRACE_SCAD = '''// Generated by trace_triskele.py -- do not edit.
// Flatten Insert-air-tribe.stl's face plane to 2D and export to DXF.
//
// This plate lies in YZ with its thickness along X, centred on native
// y = 0, z = 60. (Insert-tree.stl lies in XZ instead -- do not reuse that
// file's rotate([90,0,0]) here.)
//
// rotate(a = -120, v = [1,1,1]) cyclically maps (x,y,z) -> (y,z,x), which
// is exactly mesh_orient.orient_to_xy(axis = 0). Choosing the permutation
// that matches the helper, rather than a rotate() about a single axis,
// means the trace and every mesh-side check share one frame and there is no
// mirror to compensate for downstream: orientation_iou() scores this recipe
// at (False, False), so no flip is hidden anywhere.
//
// The translate runs first and centres the design on the origin.
projection(cut = false)
    rotate(a = -120, v = [1, 1, 1])
        translate([0, 0, -60])
            import("%s");
'''


def main():
    check_only = "--check" in sys.argv
    scad = os.path.join(HERE, "cad", ".triskele_trace.scad")
    try:
        _run(check_only, scad)
    finally:                       # intermediates never survive a run,
        for tmp in (DXF, scad):    # including an aborted or --check one
            if os.path.exists(tmp):
                os.remove(tmp)


def _run(check_only, scad):

    tris = load_stl(SRC)
    axis, lo, hi = plate_axis(tris)
    print("source      %s" % os.path.basename(SRC))
    print("plate axis  %s, thickness %.3f mm, faces at %.1f and %.1f"
          % ("XYZ"[axis], hi - lo, lo, hi))

    with open(scad, "w") as f:
        f.write(TRACE_SCAD % SRC)
    subprocess.run(["openscad", "--render", "-o", DXF, scad],
                   check=True, capture_output=True)

    polys = trace_dxf(DXF, keep=lambda rmin, rmax: rmax <= DESIGN_MAX_R)

    # --- verification 1: what do these loops mean? -------------------------
    face = load_oriented(SRC)          # faces now lie in XY, plate centred
    hits, total = sense_of(polys, face, z=FACE_Z)
    print("sense       %d/%d interior points sit on material" % (hits, total))
    if hits > total * 0.05:
        sys.exit("ABORT: expected 0 -- these are supposed to be cut-outs, which "
                 "the coaster subtracts from a disc. A majority would mean "
                 "raised artwork; anything in between means the trace mixes "
                 "both senses and must be separated first. Not a vote.")
    print("            -> cut-outs. Callers must SUBTRACT this module.")

    bad = nested(polys)
    print("nesting     %d polygons inside another (material islands)" % len(bad))
    if bad:
        sys.exit("ABORT: nested polygons would be filled in. Handle them first.")

    # --- verification 2: which way up, and which hand? ---------------------
    rows = orientation_iou(polys, face, z=FACE_Z, r_clip=47.5)
    if rows[0][0] != (False, False):
        sys.exit("ABORT: trace is mirrored -- fix TRACE_SCAD above.")
    if rows[0][1] < 0.85:
        sys.exit("ABORT: best IoU only %.3f; the trace does not match the "
                 "source well enough to trust." % rows[0][1])

    total_area = sum(polygon_area(p) for p in polys)
    rmax = max(max((x * x + y * y) ** 0.5 for x, y in p) for p in polys)
    print("geometry    %d polygons, %d points, %.2f mm^2 native "
          "(%.0f mm^2 at coaster scale), rmax %.2f native / %.2f coaster"
          % (len(polys), sum(len(p) for p in polys), total_area,
             total_area * SCALE * SCALE, rmax, rmax * SCALE))
    if abs(rmax - NATIVE_MAX_R) > 0.01:
        sys.exit("ABORT: rmax %.4f does not match NATIVE_MAX_R %.4f, which is "
                 "the coaster's scale reference." % (rmax, NATIVE_MAX_R))

    header = HEADER.replace("{n}", str(len(polys))) \
                   .replace("{tot}", "%.2f" % total_area) \
                   .replace("{sc}", "%.0f" % (total_area * SCALE * SCALE)) \
                   .replace("{rmax}", "%.2f" % rmax) \
                   .replace("{rmaxc}", "%.2f" % (rmax * SCALE)) \
                   .replace("{iou}", "%.2f" % rows[0][1])
    extra = ("native_max_r = %.4f;   // outer radius of the DESIGN, "
             "the scale reference\n\n" % NATIVE_MAX_R)

    if check_only:
        print("\n--check: verification passed, nothing written.")
        return

    emit_scad(polys, OUT, "triskele_cuts_native", header=header, extra=extra)
    print("\nwrote %s" % os.path.relpath(OUT, HERE))


HEADER = """// Exact traced outline of the CUT LINE-WORK of the Celtic triskele,
// extracted from Insert-air-tribe.stl. GENERATED by ../trace_triskele.py --
// do not hand-edit; re-run that script instead. See
// ../coaster_triskele_spec.md section 3.
//
// SENSE: these {n} polygons are the artwork's own CUT strokes. The source
// insert is a solid plate with the triskele cut clean through it, so the
// *background is the material* and the *drawing is the hole* -- the same
// sense as tree_of_life_pattern.scad, and the opposite of
// insert-yggdrasil.stl and insert-helm-of-awe.stl, whose traced polygons
// were the background instead (see coaster_yggdrasil_spec.md section 6, F1,
// for how much a mix-up of exactly this kind cost once).
//
// Verified by the generator, not assumed, and it refuses to write this file
// if either check fails:
//   1. sense: 0 of {n} polygon interior points sit on material in the source
//      mesh, so these are cut-outs: callers must SUBTRACT them from a disc.
//      (Interior points, not area centroids -- the centroid of a curved
//      ribbon falls outside it. Tree of Life spec, D9.)
//   2. orientation: rasterised against the source mesh's own cut region,
//      this trace scores IoU {iou} and the best variant is the unflipped
//      one. A triskele is chiral, so a mirror would quietly reverse the
//      direction all three spirals turn -- and area, radii, counts and
//      width distributions are every one of them identical under a flip.
//
// A caller therefore SUBTRACTS this module from a disc. That also makes the
// coaster one connected piece by construction: it is a disc with holes in
// it, so there is no scaffolding problem to solve.
//
// UNLIKE the Tree of Life, nothing here is discarded. That source's chain
// border measured 0.36 mm ribbons at coaster scale and had to be replaced
// wholesale; this design measures 2.89 mm median material in the arms and
// holds together under 0.30 mm of erosion as traced, so it is reproduced
// faithfully. The only component filtered out is the plate's own square
// border at r = 75.80 native, which is insert-specific -- every part of the
// design proper sits inside r = 47.20, so the split is not a judgement call.
// The plate's four corner marks are blind pockets, not through-holes, and
// do not appear in a projection() shadow at all.
//
// The design's outer arcs reach r = {rmax} native ({rmaxc} mm at coaster
// scale), which is the scale reference: it lands their outer edge exactly
// on the inner edge of the coaster's solid 7 mm rim.
//
// Native scale, centered on the design's own center. Callers scale/extrude.

"""

if __name__ == "__main__":
    main()
