#!/usr/bin/env python3
"""Regenerate cad/tree_of_life_pattern.scad from Insert-tree.stl.

    python3 trace_tree_of_life.py            # rebuild the pattern file
    python3 trace_tree_of_life.py --check    # verify only, write nothing

Run from coasters/. Needs OpenSCAD on PATH and Pillow. Output is
deterministic: rebuilding reproduces the pattern file, and therefore
coaster_tree_of_life.stl, byte for byte.

This is the worked example for utilities/pattern_trace.py, and it exists
because the two earlier coasters' pattern files cannot be regenerated --
their extraction was done by hand and the script was never kept, so the
generated .scad is the only copy of a decision nobody can re-derive.

The two verification steps in the middle are not ceremony. Every coaster in
this repo has had one of them come out wrong:

  * SENSE -- are the traced loops the artwork, or the hole around it? Here
    they are the artwork (this source is a plate with the design cut
    through), which is the opposite of the other two inserts.
  * ORIENTATION -- projection() after rotate([90,0,0]) lands vertically
    mirrored, which stood this tree on its head through several rounds of
    measurement because every derived number is identical under a mirror.
"""
import os
import subprocess
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "utilities"))

from mesh_orient import load_oriented, plate_axis                  # noqa: E402
from pattern_trace import (emit_scad, nested, orientation_iou,     # noqa: E402
                           sense_of, trace_dxf)
from dxf_trace import polygon_area                                 # noqa: E402
from stl_io import load_stl                                        # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "Insert-tree.stl")
OUT = os.path.join(HERE, "cad", "tree_of_life_pattern.scad")
DXF = os.path.join(HERE, "cad", ".tree_trace.dxf")      # intermediate

# The design's own outer radius (the source chain ring's outer edge). This is
# the scale reference the coaster uses to land the pattern at r = 43.
NATIVE_MAX_R = 47.2812
TARGET_R = 43.0
SCALE = TARGET_R / NATIVE_MAX_R

# Tree components have rmin <= 30.08 and the discarded chain ring's have
# rmin >= 41.63, so this threshold sits in a wide empty gap.
TREE_SPLIT_R = 39.0

TRACE_SCAD = '''// Generated by trace_tree_of_life.py -- do not edit.
// Flatten Insert-tree.stl's face plane to 2D and export to DXF.
//
// The plate lies in XZ (thickness along Y), so rotate([90,0,0]) brings its
// face into XY and translate([0,0,-60]) centres it on the design's own
// centre (native z = 60).
//
// The mirror() is NOT cosmetic. rotate([90,0,0]) maps (x,y,z) -> (x,-z,y),
// so the projection lands at (x, 60-z): vertically flipped relative to the
// plate as drawn, which stands the Tree of Life on its head. Verified by
// orientation_iou(), not by eye -- see utilities/pattern_trace.py.
mirror([0, 1, 0])
projection(cut = false)
    rotate([90, 0, 0])
        translate([0, 0, -60])
            import("%s");
'''


def main():
    check_only = "--check" in sys.argv
    scad = os.path.join(HERE, "cad", ".tree_trace.scad")
    try:
        _run(check_only, scad)
    finally:                       # intermediates never survive a run,
        for tmp in (DXF, scad):    # including an aborted or --check one
            if os.path.exists(tmp):
                os.remove(tmp)


def _run(check_only, scad):

    tris = load_stl(SRC)
    axis, lo, hi = plate_axis(tris)
    print("source      %s" % os.path.basename(SRC))
    print("plate axis  %s, thickness %.3f mm, faces at %.1f and %.1f"
          % ("XYZ"[axis], hi - lo, lo, hi))

    with open(scad, "w") as f:
        f.write(TRACE_SCAD % SRC)
    subprocess.run(["openscad", "--render", "-o", DXF, scad],
                   check=True, capture_output=True)

    polys = trace_dxf(DXF, keep=lambda rmin, rmax: rmin <= TREE_SPLIT_R)

    # --- verification 1: what do these loops mean? -------------------------
    face = load_oriented(SRC)          # faces now lie in XY, plate centred
    hits, total = sense_of(polys, face, z=lo)
    print("sense       %d/%d interior points sit on material" % (hits, total))
    if hits > total * 0.05:
        sys.exit("ABORT: expected 0 -- these are supposed to be cut-outs, which "
                 "the coaster subtracts from a disc. A majority would mean "
                 "raised artwork; anything in between means the trace mixes "
                 "both senses and must be separated first. Not a vote.")
    print("            -> cut-outs. Callers must SUBTRACT this module.")

    bad = nested(polys)
    print("nesting     %d polygons inside another (material islands)" % len(bad))
    if bad:
        sys.exit("ABORT: nested polygons would be filled in. Handle them first.")

    # --- verification 2: which way up? ------------------------------------
    rows = orientation_iou(polys, face, z=lo, r_clip=41.3)
    if rows[0][0] != (False, False):
        sys.exit("ABORT: trace is mirrored -- fix TRACE_SCAD above.")
    if rows[0][1] < 0.85:
        sys.exit("ABORT: best IoU only %.3f; the trace does not match the "
                 "source well enough to trust." % rows[0][1])

    total_area = sum(polygon_area(p) for p in polys)
    rmax = max(max((x * x + y * y) ** 0.5 for x, y in p) for p in polys)
    print("geometry    %d polygons, %d points, %.2f mm^2 native "
          "(%.0f mm^2 at coaster scale), rmax %.2f native / %.2f coaster"
          % (len(polys), sum(len(p) for p in polys), total_area,
             total_area * SCALE * SCALE, rmax, rmax * SCALE))

    header = HEADER.replace("{n}", str(len(polys))) \
                   .replace("{tot}", "%.2f" % total_area) \
                   .replace("{sc}", "%.0f" % (total_area * SCALE * SCALE)) \
                   .replace("{rmax}", "%.2f" % rmax) \
                   .replace("{rmaxc}", "%.2f" % (rmax * SCALE)) \
                   .replace("{iou}", "%.2f" % rows[0][1])
    extra = ("native_max_r = %.4f;   // outer radius of the SOURCE ring, "
             "the scale reference\n\n" % NATIVE_MAX_R)

    if check_only:
        print("\n--check: verification passed, nothing written.")
        return

    emit_scad(polys, OUT, "tree_of_life_cuts_native", header=header, extra=extra)
    print("\nwrote %s" % os.path.relpath(OUT, HERE))


HEADER = """// Exact traced outline of the CUT LINE-WORK of the Celtic Tree of Life,
// extracted from Insert-tree.stl. GENERATED by ../trace_tree_of_life.py --
// do not hand-edit; re-run that script instead. See
// ../coaster_tree_of_life_spec.md section 3.
//
// READ THE SENSE CAREFULLY -- it is the OPPOSITE of the other two coasters
// in this set. These {n} polygons are the artwork's own CUT strokes: the
// source insert is a solid plate with the tree's knotwork cut clean through
// it, so here the *background is the material* and the *drawing is the
// hole*. In insert-yggdrasil.stl and insert-helm-of-awe.stl the traced
// polygons were the background instead (see coaster_yggdrasil_spec.md
// section 6, F1, for how much a mix-up of exactly this kind cost once).
//
// Verified by the generator, not assumed, and it refuses to write this file
// if either check fails:
//   1. sense: 0 of {n} polygon interior points sit on material in the source
//      mesh, so these are cut-outs: callers must SUBTRACT them from a disc.
//      (Interior points, not area centroids -- the centroid of a curved
//      ribbon falls outside it, and that version answered 28 of 62. D9.)
//   2. orientation: rasterised against the source mesh's own cut region,
//      this trace scores IoU {iou}; the vertically mirrored alternative
//      scores 0.28. projection() after rotate([90,0,0]) lands mirrored, and
//      no derived number would have told us -- area, radii, counts and width
//      distributions are all identical under a flip.
//
// A caller therefore SUBTRACTS this module from a disc. A caller that
// extruded it directly would print the tree as a floating pile of loose
// knot fragments -- these polygons do not touch each other.
//
// The chain ring that surrounds the tree in the source is deliberately NOT
// here: at coaster scale its material ribbons measure 0.36 mm, far below
// anything FDM can hold together, and it is replaced wholesale by
// celtic_chain_ring.scad. This file holds the tree only, split off by a
// threshold on each component's MINIMUM radius: the tree's components have
// rmin <= 30.08 and the ring's have rmin >= 41.63, so the cut at 39 falls in
// a wide empty gap and is not a judgement call.
//
// The tree's own reach is larger than that split suggests, and this is the
// number that constrains the new ring: its two big root sweeps run out to
// r = {rmax} native ({rmaxc} mm at coaster scale), leaving only ~0.6 mm of
// material to where the source ring began. See celtic_chain_ring.scad.
//
// 3 of these {n} components had a self-touching vertex that defeats
// dxf_trace.walk_polygon (its documented C2 failure mode). They were
// repaired by planar face tracing rather than dropped -- spec section 6, D3.
//
// Native scale, centered on the design's own center. Callers scale/extrude.

"""

if __name__ == "__main__":
    main()
